org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
java_version=17
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.17
forge_version_range=[47.4.17,48)
loader_version_range=[47,48)
mapping_channel=official
# The mapping version to query from the mapping channel.
# This must match the format required by the mapping channel.
mapping_version=1.20.1
# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=appliedtacz
mod_loader=forge
# The human-readable display name for the mod.
mod_name=AppliedTaCZ
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=GNU GPL 3.0
# The mod version. See https://semver.org/
mod_version=0.0.1
mod_version_type=release
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=me.myogoo
archives_base_name=AppliedTaCZ
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=NJoyShadow
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=AE2-powered TaCZ workbenches that can view and consume crafting materials from the ME network.

AE2_version=15.4.10
AE2_version_range=[15.4.10,15.5)
TaCZ_version_range=[1.1.7,1.2)
AE2WTLib_version=15.2.3
JEI_version=15.20.0.112
guideME_version=20.1.11
